image: python:3.14-slim

variables:
    UV_CACHE_DIR: .uv-cache
    REPORT_PATH: report.xml

cache:
    key:
        files:
            - uv.lock
    paths:
        - $UV_CACHE_DIR

stages:
    - test

run_tests:
    stage: test
    before_script:
        - pip install uv
    script:
        - uv sync --locked
        - uv run pytest tests/ --junitxml=$REPORT_PATH
    artifacts:
        when: always
        reports:
            junit: $REPORT_PATH
